node('php')  {
         stage 'BuildDev'
         openshiftBuild(namespace: 'php-dev', buildConfig: 'php-example', showBuildLogs: 'true')
         stage 'VerifyBuild'
         openshiftVerifyBuild(namespace: 'php-dev', buildConfig: 'php-example') 
         stage 'DeployTest'
         openshiftDeploy(namespace: 'php-dev', deploymentConfig: 'php-example', showBuildLogs: 'true')
         stage 'VerifyDeploymentTest'
         openshiftVerifyDeployment(namespace: 'php-dev', deploymentConfig: 'php-example')
         stage('Promote to Test?') {
                  timeout(time:15, unit:'MINUTES') {
                      input message: "Promote to Test?", ok: "Promote"
                }
                openshiftTag(namespace: 'php-dev', sourceStream: 'php-example', sourceTag: 'latest', destinationNamespace: 'php-test', destinationStream: 'php-example', destinationTag: 'latest')
                openshiftDeploy(namespace: 'php-test', deploymentConfig: 'php-example', showBuildLogs: 'true')
         }
} 
