apiVersion: v1
kind: BuildConfig
metadata:
  name: example1
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |
        node('maven')  
        {
         stage 'Build'
         openshiftBuild(namespace: 'thisproject', buildConfig: 'buildconfigname', showBuildLogs: 'true')
         stage 'Deploy'
         openshiftDeploy(namespace: 'thisproject', deploymentConfig: 'deployconfigname')
         stage 'Scale'   
         openshiftScale(namespace: 'cicdprod', deploymentConfig: 'nodetest',replicaCount: '6')
        }
