apiVersion: v1
kind: BuildConfig
metadata:
  name: example1
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |
        node('maven')  
        {
         stage 'Build'
         openshiftBuild(namespace: 'simplepipeline', buildConfig: 'nodetest', showBuildLogs: 'true')
         stage 'Deploy'
         openshiftDeploy(namespace: 'simplepipeline', deploymentConfig: 'nodetest')
         stage 'Scale'   
         openshiftScale(namespace: 'simplepipeline', deploymentConfig: 'nodetest', replicaCount: '4')
        }
