kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "crossProject1"
spec:
  source:
    git:
      uri: "https://github.com/utherp0/pipelineExamples"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: example1/pipeline1.jenkins 
