kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "pipelinefromgit"
spec:
  source:
    git:
      uri: "https://github.com/utherp0/pipelineExamples"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: example1/examplePipeline.jenkins 
