kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "pipelinefromgit"
spec:
  source:
    git:
      uri: "https://github.com/blues-man/edp-pipeline"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipeline/edppipeline.jenkins 
